#pragma once

#include "data/ai_controller.h"
#include "data/cosmetic_slot.h"
#include "data/css_slot.h"
#include "data/fighter_constants.h"
#include "data/fighter_name.h"
#include "data/fighter_res_data.h"
#include "data/fighter_resource_path.h"
#include "data/ft_class_info.h"
#include "data/ft_extend_param_accessor.h"
#include "data/kirby_resource_path.h"
#include "data/records.h"
#include "data/rel_filename.h"
#include "data/slot.h"
#include "data/soundbanks.h"
#include "data/texture_load_functions.h"
#include "data/victory_announcer.h"
#include "data/victory_camera.h"
#include "data/victory_name.h"
#include "data/victory_song.h"

#include "data/flags/entry_article_flags.h"
#include "data/flags/entry_resource_flags.h"
#include "data/flags/fighter_color_flags.h"
#include "data/flags/fighter_load_flags.h"
#include "data/flags/final_resource_flags.h"
#include "data/flags/kirby_resource_flags.h"
#include "data/flags/result_resource_flags.h"

#include "data/strings/ftInternalNames.h"
#include "data/strings/ftOverlayStrings.h"
#include "data/strings/ftResourceStrings.h"
#include "data/strings/kirbyResourceStrings.h"
#include "data/strings/victoryNames.h"
